---
title: "lab05-Betty-Cui"
author: "Betty Cui"
date: "2/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../images/')
github <- "https://github.com/ucb-stat133/stat133-fall-2017/raw/master/"
csv <- "data/nba2017-players.csv"
download.file(url = paste0(github, csv), destfile = 'nba2017-players.csv')
dat <-read.csv('nba2017-players.csv', stringsAsFactors = FALSE)
```

```{r read, eval = TRUE}
# with "base" read.csv()
dat <- read.csv('nba2017-players.csv', stringsAsFactors = FALSE)
```

```{r}
three_rows <- slice(dat, 1:3)
three_rows
gt_85 <- filter(dat, height > 85)
gt_85
player_height <- select(dat, player, height)
```

#My turn
```{r}
five_rows <- slice(dat, 1:5)
five_rows
rows_selected <- slice(dat, seq(from = 10, to = 50, by = 10))
rows_selected
last_fiverows <- slice(dat, 437:441)
last_fiverows
gt_70 <- filter(dat, height <70)
gt_70
GSW_teams <- filter(dat, team == "GSW")
GSW_teams
GSW_C <- filter(dat, team == "C")
GSW_C
Lakers <- filter(dat, team == "LAL")
select(Lakers, player)
GSWPG <- filter(dat, team == "GSW" & position == "PG")
select(GSWPG, player)
select(filter(dat, salary_millions <= 10, experience > 10), age, player, team)
slice(select(filter(dat, experience == 0 & age == 20), player, team, height, weight),1:5)
```

```{r}
gsw <- filter(dat, team == 'GSW')
gsw <- select(gsw, player, height, weight)
gsw <- slice(gsw, c(4, 8, 10, 14, 15))
gsw
gsw2 <- mutate(gsw, ht_m = height * 0.0254, wt_kg = weight * 0.4536)
gsw2
arrange(gsw, height)
arrange(gsw, desc(height))
arrange(gsw, height, weight)
```

#My Turn
```{r}
mutate(gsw, product = height*weight)
gsw3 <- mutate(gsw, log_weight = log(weight), log_height = log(height))
gsw3
arrange(filter(dat, height < 71), height)
highest_paid <- select(dat, player, team, salary)
highest_paid <- arrange(highest_paid, desc(salary))
highest_paid <- slice(highest_paid, 1:5)
highest_paid
three_points <- select(dat, player, team, points3)
three_points <- arrange(three_points, desc(points3))
three_points <- slice(three_points, 1:10)
three_points
gsw_mgp <- filter(dat, team == "GSW")
gsw_mgp <- mutate(gsw_mgp, min_per_game = minutes/games)
gsw_mgp <- select(gsw_mgp, player, experience, min_per_game)
gsw_mgp <-arrange(gsw_mgp, desc(min_per_game))
gsw_mgp
```

```{r}
summarise(dat, avg_salary = mean(salary))
mean(dat$salary)
c(min = min(dat$salary), 
  median = median(dat$salary),
  median = mean(dat$salary),
  max = max(dat$salary))
summarise(
  group_by(dat, team),
  avg_salary = mean(salary)
)
summarise(
  group_by(dat, position),
  avg_salary = mean(salary)
)
arrange(
  summarise(
    group_by(dat, position),
    avg_height = mean(height),
    avg_weight = mean(weight)),
  desc(avg_height)
)
```

#My turn
```{r}
summarise(dat, max_height = max(height))
summarise(dat, sd3 = sd(points3))
summarise(
  group_by(dat, team),
  median(points3)
)
three_point <- summarise(
  group_by(dat, team),
  avg_3 = mean(points3)
)
three_point <- arrange(three_point, avg_3)
slice(three_point, 1:5)

smr_age <- filter(dat, experience >= 5 & experience <= 10)
smr_age <- summarise(
  group_by(smr_age, position),
  mean(age),
  sd(age)
)
smr_age <- filter(smr_age, position == "PF")
smr_age
```

```{r}
ggplot(data = dat) +
  geom_point(aes(x = points, y = salary))
ggplot(data = dat, aes(x = points, y = salary)) +
  geom_point()
```

#My turn
```{r}
ggplot(data = gsw, aes(x = height, y = weight)) +
  geom_point()
ggplot(data = gsw, aes(x = height, y = weight)) +
  geom_point()+
  geom_text(aes(label = player), position = "identity")
gsw4 <-  filter(dat, team == "GSW")
gsw4 <- select(gsw4, player, height, weight)
ggplot(data = gsw4, aes(x = height, y = weight))+
  geom_point()+
  geom_label(aes(label = player))
ggplot(data = dat, aes(x = salary))+
  geom_density(aes(salary))
ggplot(data = dat, aes(x = points2))+
  geom_histogram(binwidth = 50)
ggplot(data = dat, aes(x = position))+
  geom_bar()
all_centers <- filter(dat, position == "C")
ggplot(data = all_centers, aes(x = experience, y = salary)) +
  geom_point() +
  geom_smooth(method = "lm")
ggplot(data = all_centers, aes(x = experience, y = salary)) +
  geom_point()+
  geom_smooth()
```

#My turn
```{r}
library(ggplot2)
ggplot(data = dat, aes(x = experience, y = salary)) +
  geom_point(aes(color = position)) +
  facet_wrap(~position)
library(ggplot2)
ggplot(data = dat, aes(x = experience, y = salary)) +
  geom_point(aes(color = position)) +
  facet_wrap(~team)
ggplot(data = dat, aes(x = age))+
  geom_density(aes(color = team)) +
  facet_wrap(~team)
ggplot(data = dat, aes(x = height, y = weight)) +
  geom_point(aes(color = position)) +
  facet_grid(~position)
ggplot(data = dat, aes(x = height, y = weight)) +
  geom_point(aes(color = position)) +
  geom_density_2d()+
  facet_wrap(~position)
```