---
title: "hw03-Betty-Cui"
author: "Betty Cui"
date: "3/18/2018"
output: github_document
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, error =  FALSE, fig.path = 'images/')
```


```{bash}
## 2.1 Writing a pipeline to obtain the uniqeu team names, and redirect the output to a text file team-names.txt
cut -d "," -f 2 nba2017-roster.csv | tail +2 > team-names.txt
sort team-names.txt | uniq -c | head -n 5
```
```{bash}
## 2.2 Writing a pipeline to obtain the unique positions, and redirect the txt file to position-names.txt
cut -d "," -f 3 nba2017-roster.csv  > position-names.txt
sort position-names.txt | uniq -c | head -n 5
```

```{bash}
## 2.3 Write a pipeline to obtain the counts of the different experience value from largest to smallest and redirect the output to a textfile experience-counts.txt
cut -d "," -f 7 nba2017-roster.csv | tail +2| sort | uniq -c| sort -r > experience-counts.txt
head -5 experience-counts.txt
```


```{bash}
## 2.4 Containing data for LAC team
head -n 1 nba2017-roster.csv > LAC.csv
grep 'LAC' nba2017-roster.csv >> LAC.csv
cat LAC.csv
```

```{bash}
## 2.5 Write a pipeline ti display the age of frequencies of LAL players
grep "LAL" nba2017-roster.csv | cut -d "," -f 6 | tail +2| sort | uniq -c
```

```{bash}
## 2.6) Write a pipeline to find the number of players in CLE
grep "CLE" nba2017-roster.csv | wc -l
```

```{bash}
## 2.7) Write pipelines to create a CSV file gsw-height-weight.csv
head -1 nba2017-roster.csv | cut -d "," -f 1,4,5 > gsw-height-weight.csv
grep "GSW" nba2017-roster.csv | cut -d "," -f 1,4,5 >> gsw-height-weight.csv
cat gsw-height-weight.csv
```

```{bash}
cut -d "," -f 1,8 nba2017-roster.csv | head -1 > top10-salaries.csv
cut -d "," -f 1,8 nba2017-roster.csv  | tail +2 | sort -n -r -t"," -k 2 | head -10 >> top10-salaries.csv
cat top10-salaries.csv
```

```{r}
source("code/binomial-function.R")
```

```{r}
bin_probability(10, 3, 1/6)
bin_distribution(10, 0.25)
```
```{r}
prob1 = 0
for (i in 3:5){
prob1 = prob1 + bin_probability(5, i, 0.35)
}
prob1
```

```{r}
bin_distribution(15, 0.35)
plot(bin_distribution(15, 0.35))
```


